# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tree_number', models.IntegerField(default=0)),
                ('subsystem_code', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('team_member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
