# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0003_productitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Unnamed', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Occurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurence_name', models.CharField(default='Unnamed', max_length=200)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2017, 7, 6, 8, 23, 23, 7590, tzinfo=utc))),
                ('attendee', models.ManyToManyField(to='juice_calendar.Profile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juice_calendar.Event')),
            ],
        ),
        migrations.RenameField(
            model_name='productitem',
            old_name='name',
            new_name='product_item_name',
        ),
        migrations.AddField(
            model_name='event',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juice_calendar.ProductItem'),
        ),
    ]
