# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0004_auto_20170629_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurence',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 7200)),
        ),
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 8, 32, 11, 256092, tzinfo=utc)),
        ),
    ]
