# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 07:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0005_auto_20170629_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 7, 7, 7, 55, 592982, tzinfo=utc)),
        ),
    ]
