# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0009_auto_20170630_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 6, 45, 27, 532328, tzinfo=utc)),
        ),
    ]
