# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0010_auto_20170703_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 13, 38, 57, 794119, tzinfo=utc)),
        ),
    ]
