# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 06:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0011_auto_20170703_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 6, 21, 52, 904740, tzinfo=utc)),
        ),
    ]
