# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0017_auto_20170705_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 12, 9, 30, 55, 637031, tzinfo=utc)),
        ),
    ]
