# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 05:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0018_auto_20170705_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 5, 52, 33, 13762, tzinfo=utc)),
        ),
    ]
