# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 06:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0019_auto_20170710_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 6, 53, 54, 722271, tzinfo=utc)),
        ),
    ]
