# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 08:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0020_auto_20170710_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='parent_system',
            field=models.ForeignKey(null='TRUE', on_delete=django.db.models.deletion.CASCADE, to='juice_calendar.ProductItem'),
        ),
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 8, 30, 6, 247305, tzinfo=utc)),
        ),
    ]
