# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0023_auto_20170710_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='parent_system',
            new_name='sub_system',
        ),
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 11, 30, 10, 146497, tzinfo=utc)),
        ),
    ]
