# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0024_auto_20170710_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 12, 24, 23, 581530, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='sub_system',
        ),
        migrations.AddField(
            model_name='productitem',
            name='sub_system',
            field=models.ManyToManyField(related_name='_productitem_sub_system_+', to='juice_calendar.ProductItem'),
        ),
    ]
