# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 06:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0029_auto_20170712_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 6, 13, 40, 774386, tzinfo=utc)),
        ),
    ]
