# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 06:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0030_auto_20170713_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurence',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 6, 29, 40, 413659, tzinfo=utc)),
        ),
    ]
