# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0032_auto_20170713_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 9, 40, 49, 617605, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='subsystem_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
