# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0033_auto_20170717_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('TELC', 'Telecon'), ('REV', 'Review'), ('MEET', 'Meeting'), ('TEST', 'Test')], default='Meeting', max_length=4),
        ),
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 26, 13, 11, 32, 931918, tzinfo=utc)),
        ),
    ]
