# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0036_auto_20170724_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 31, 9, 24, 42, 706231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 31, 9, 24, 42, 707488, tzinfo=utc)),
        ),
    ]
