# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0037_auto_20170724_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 8, 8, 5, 717614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 8, 8, 5, 718867, tzinfo=utc)),
        ),
    ]
