# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-07 06:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0039_auto_20170801_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='responsable',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='juice_calendar.Profile'),
        ),
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 6, 25, 50, 198330, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 6, 25, 50, 200623, tzinfo=utc)),
        ),
    ]
