# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0045_auto_20170814_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 12, 44, 23, 216209, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 12, 44, 23, 218629, tzinfo=utc)),
        ),
    ]
