# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0046_auto_20170814_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 12, 52, 45, 740128, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 12, 52, 45, 742449, tzinfo=utc)),
        ),
    ]
