# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0047_auto_20170814_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 6, 24, 12, 797628, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 6, 24, 12, 804005, tzinfo=utc)),
        ),
    ]
