# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juice_calendar', '0049_auto_20170821_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 6, 15, 9, 798639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 29, 6, 15, 9, 800763, tzinfo=utc)),
        ),
    ]
